export const SET_NEXT_EVENT = 'SET_NEXT_EVENT';
export const SET_FETCHING = 'SET_FETCHING';
export const HOME_DISPLAY_PROFILE = 'HOME_DISPLAY_PROFILE';
export const HOME_DISMISS_PROFILE = 'HOME_DISMISS_PROFILE';
