export const OPEN_MIC_NAME = 'OPEN_MIC_NAME';
export const OPEN_MIC_TOPIC = 'OPEN_MIC_TOPIC';
export const OPEN_MIC_IS_LOADING = 'OPEN_MIC_IS_LOADING';
export const CLEAR_OPEN_MIC = 'CLEAR_OPEN_MIC';
